name: Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
    steps:
      - uses: actions/checkout@v1
      - run: npm i
      - run: npm run build
      - run: chmod +x ./lib/cli.js
      - run: npm test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
